#!/usr/bin/env python3

import sys
import minivm.assemble
import minivm.disassemble


def print_usage(prog):
    print(f"""\
Commands:

  {prog} assemble INPUT_FILE OUTPUT_FILE
    (alias: {prog} as)

  {prog} disassemble INPUT_FILE [OUTPUT_FILE]
    (alias: {prog} dis)

  {prog} run INPUT_FILE
""")


def main():
    prog = sys.argv[0]
    if len(sys.argv) < 2:
        print_usage(prog)
        sys.exit(1)

    cmd = sys.argv[1]
    sys.argv[0] = sys.argv[0] + ' ' + sys.argv[1]
    sys.argv.pop(1)

    if cmd in ['assemble', 'as']:
        minivm.assemble.main()
    elif cmd in ['disassemble', 'dis']:
        minivm.disassemble.main()
    else:
        print_usage(prog)
        sys.exit(1)


if __name__ == "__main__":
    main()
